# Generated by Django 4.1.4 on 2022-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accommodation_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='num_of_guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.IntegerField(),
        ),
    ]
